/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SoulRegistry } from "./SoulRegistry";
export * as factories from "./factories";
export { SoulRegistry__factory } from "./factories/SoulRegistry__factory";
