/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SoulRegistry {
  export type DocumentEntryStruct = {
    contentHash: BytesLike;
    encryptedHash: BytesLike;
    storageCid: string;
    docType: BigNumberish;
    timestamp: BigNumberish;
    version: BigNumberish;
    prevHash: BytesLike;
    signature: BytesLike;
  };

  export type DocumentEntryStructOutput = [
    contentHash: string,
    encryptedHash: string,
    storageCid: string,
    docType: bigint,
    timestamp: bigint,
    version: bigint,
    prevHash: string,
    signature: string
  ] & {
    contentHash: string;
    encryptedHash: string;
    storageCid: string;
    docType: bigint;
    timestamp: bigint;
    version: bigint;
    prevHash: string;
    signature: string;
  };
}

export interface SoulRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "children"
      | "documentAt"
      | "documentCount"
      | "getAccessKey"
      | "getChildren"
      | "getParent"
      | "grantAccess"
      | "hasAccess"
      | "latestDocument"
      | "parent"
      | "registerChild"
      | "registerSoul"
      | "registered"
      | "removeAccessKey"
      | "revokeAccess"
      | "storeAccessKey"
      | "verifyDocument"
      | "writeDocument"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AccessGranted"
      | "AccessKeyStored"
      | "AccessRevoked"
      | "ChildRegistered"
      | "DocumentWritten"
      | "SoulRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "children",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "documentAt",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "documentCount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccessKey",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChildren",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getParent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAccess",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestDocument",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "parent", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "registerChild",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSoul",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAccessKey",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storeAccessKey",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocument",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "writeDocument",
    values: [BigNumberish, BytesLike, BytesLike, string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "children", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "documentAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "documentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccessKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChildren",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getParent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasAccess", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "parent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerChild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSoul",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAccessKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeAccessKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "writeDocument",
    data: BytesLike
  ): Result;
}

export namespace AccessGrantedEvent {
  export type InputTuple = [
    agent: AddressLike,
    reader: AddressLike,
    docType: BigNumberish
  ];
  export type OutputTuple = [agent: string, reader: string, docType: bigint];
  export interface OutputObject {
    agent: string;
    reader: string;
    docType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessKeyStoredEvent {
  export type InputTuple = [
    owner: AddressLike,
    reader: AddressLike,
    docType: BigNumberish
  ];
  export type OutputTuple = [owner: string, reader: string, docType: bigint];
  export interface OutputObject {
    owner: string;
    reader: string;
    docType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AccessRevokedEvent {
  export type InputTuple = [
    agent: AddressLike,
    reader: AddressLike,
    docType: BigNumberish
  ];
  export type OutputTuple = [agent: string, reader: string, docType: bigint];
  export interface OutputObject {
    agent: string;
    reader: string;
    docType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChildRegisteredEvent {
  export type InputTuple = [parent: AddressLike, child: AddressLike];
  export type OutputTuple = [parent: string, child: string];
  export interface OutputObject {
    parent: string;
    child: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentWrittenEvent {
  export type InputTuple = [
    agent: AddressLike,
    docType: BigNumberish,
    version: BigNumberish,
    contentHash: BytesLike,
    storageCid: string
  ];
  export type OutputTuple = [
    agent: string,
    docType: bigint,
    version: bigint,
    contentHash: string,
    storageCid: string
  ];
  export interface OutputObject {
    agent: string;
    docType: bigint;
    version: bigint;
    contentHash: string;
    storageCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoulRegisteredEvent {
  export type InputTuple = [agent: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [agent: string, timestamp: bigint];
  export interface OutputObject {
    agent: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SoulRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SoulRegistry;
  waitForDeployment(): Promise<this>;

  interface: SoulRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  children: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  documentAt: TypedContractMethod<
    [agent: AddressLike, docType: BigNumberish, version: BigNumberish],
    [SoulRegistry.DocumentEntryStructOutput],
    "view"
  >;

  documentCount: TypedContractMethod<
    [agent: AddressLike, docType: BigNumberish],
    [bigint],
    "view"
  >;

  getAccessKey: TypedContractMethod<
    [owner: AddressLike, reader: AddressLike, docType: BigNumberish],
    [string],
    "view"
  >;

  getChildren: TypedContractMethod<[agent: AddressLike], [string[]], "view">;

  getParent: TypedContractMethod<[agent: AddressLike], [string], "view">;

  grantAccess: TypedContractMethod<
    [reader: AddressLike, docType: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasAccess: TypedContractMethod<
    [agent: AddressLike, reader: AddressLike, docType: BigNumberish],
    [boolean],
    "view"
  >;

  latestDocument: TypedContractMethod<
    [agent: AddressLike, docType: BigNumberish],
    [SoulRegistry.DocumentEntryStructOutput],
    "view"
  >;

  parent: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  registerChild: TypedContractMethod<
    [child: AddressLike],
    [void],
    "nonpayable"
  >;

  registerSoul: TypedContractMethod<[], [void], "nonpayable">;

  registered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  removeAccessKey: TypedContractMethod<
    [reader: AddressLike, docType: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokeAccess: TypedContractMethod<
    [reader: AddressLike, docType: BigNumberish],
    [void],
    "nonpayable"
  >;

  storeAccessKey: TypedContractMethod<
    [reader: AddressLike, docType: BigNumberish, encryptedKey: BytesLike],
    [void],
    "nonpayable"
  >;

  verifyDocument: TypedContractMethod<
    [
      agent: AddressLike,
      docType: BigNumberish,
      version: BigNumberish,
      expectedHash: BytesLike
    ],
    [boolean],
    "view"
  >;

  writeDocument: TypedContractMethod<
    [
      docType: BigNumberish,
      contentHash: BytesLike,
      encryptedHash: BytesLike,
      storageCid: string,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "children"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "documentAt"
  ): TypedContractMethod<
    [agent: AddressLike, docType: BigNumberish, version: BigNumberish],
    [SoulRegistry.DocumentEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "documentCount"
  ): TypedContractMethod<
    [agent: AddressLike, docType: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccessKey"
  ): TypedContractMethod<
    [owner: AddressLike, reader: AddressLike, docType: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChildren"
  ): TypedContractMethod<[agent: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getParent"
  ): TypedContractMethod<[agent: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantAccess"
  ): TypedContractMethod<
    [reader: AddressLike, docType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasAccess"
  ): TypedContractMethod<
    [agent: AddressLike, reader: AddressLike, docType: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "latestDocument"
  ): TypedContractMethod<
    [agent: AddressLike, docType: BigNumberish],
    [SoulRegistry.DocumentEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "parent"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerChild"
  ): TypedContractMethod<[child: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerSoul"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeAccessKey"
  ): TypedContractMethod<
    [reader: AddressLike, docType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeAccess"
  ): TypedContractMethod<
    [reader: AddressLike, docType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeAccessKey"
  ): TypedContractMethod<
    [reader: AddressLike, docType: BigNumberish, encryptedKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDocument"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      docType: BigNumberish,
      version: BigNumberish,
      expectedHash: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "writeDocument"
  ): TypedContractMethod<
    [
      docType: BigNumberish,
      contentHash: BytesLike,
      encryptedHash: BytesLike,
      storageCid: string,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AccessGranted"
  ): TypedContractEvent<
    AccessGrantedEvent.InputTuple,
    AccessGrantedEvent.OutputTuple,
    AccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "AccessKeyStored"
  ): TypedContractEvent<
    AccessKeyStoredEvent.InputTuple,
    AccessKeyStoredEvent.OutputTuple,
    AccessKeyStoredEvent.OutputObject
  >;
  getEvent(
    key: "AccessRevoked"
  ): TypedContractEvent<
    AccessRevokedEvent.InputTuple,
    AccessRevokedEvent.OutputTuple,
    AccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ChildRegistered"
  ): TypedContractEvent<
    ChildRegisteredEvent.InputTuple,
    ChildRegisteredEvent.OutputTuple,
    ChildRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DocumentWritten"
  ): TypedContractEvent<
    DocumentWrittenEvent.InputTuple,
    DocumentWrittenEvent.OutputTuple,
    DocumentWrittenEvent.OutputObject
  >;
  getEvent(
    key: "SoulRegistered"
  ): TypedContractEvent<
    SoulRegisteredEvent.InputTuple,
    SoulRegisteredEvent.OutputTuple,
    SoulRegisteredEvent.OutputObject
  >;

  filters: {
    "AccessGranted(address,address,uint8)": TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;
    AccessGranted: TypedContractEvent<
      AccessGrantedEvent.InputTuple,
      AccessGrantedEvent.OutputTuple,
      AccessGrantedEvent.OutputObject
    >;

    "AccessKeyStored(address,address,uint8)": TypedContractEvent<
      AccessKeyStoredEvent.InputTuple,
      AccessKeyStoredEvent.OutputTuple,
      AccessKeyStoredEvent.OutputObject
    >;
    AccessKeyStored: TypedContractEvent<
      AccessKeyStoredEvent.InputTuple,
      AccessKeyStoredEvent.OutputTuple,
      AccessKeyStoredEvent.OutputObject
    >;

    "AccessRevoked(address,address,uint8)": TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;
    AccessRevoked: TypedContractEvent<
      AccessRevokedEvent.InputTuple,
      AccessRevokedEvent.OutputTuple,
      AccessRevokedEvent.OutputObject
    >;

    "ChildRegistered(address,address)": TypedContractEvent<
      ChildRegisteredEvent.InputTuple,
      ChildRegisteredEvent.OutputTuple,
      ChildRegisteredEvent.OutputObject
    >;
    ChildRegistered: TypedContractEvent<
      ChildRegisteredEvent.InputTuple,
      ChildRegisteredEvent.OutputTuple,
      ChildRegisteredEvent.OutputObject
    >;

    "DocumentWritten(address,uint8,uint32,bytes32,string)": TypedContractEvent<
      DocumentWrittenEvent.InputTuple,
      DocumentWrittenEvent.OutputTuple,
      DocumentWrittenEvent.OutputObject
    >;
    DocumentWritten: TypedContractEvent<
      DocumentWrittenEvent.InputTuple,
      DocumentWrittenEvent.OutputTuple,
      DocumentWrittenEvent.OutputObject
    >;

    "SoulRegistered(address,uint64)": TypedContractEvent<
      SoulRegisteredEvent.InputTuple,
      SoulRegisteredEvent.OutputTuple,
      SoulRegisteredEvent.OutputObject
    >;
    SoulRegistered: TypedContractEvent<
      SoulRegisteredEvent.InputTuple,
      SoulRegisteredEvent.OutputTuple,
      SoulRegisteredEvent.OutputObject
    >;
  };
}
